# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea028bb6fb59f9c01120e1d4e47e67b3edbd2f86aeffb935465c48d4a6ff1e26ab6b8eb1a27c5605521c64c38ffdb8adfc70209577c737f3444483d41c0fcee0

test:
  secret_key_base: 4277a641f505562001c354bf94e843984e1b3c96f5d203495e8270e99bb77787561e28d99df8a5555704a4276485f5318540e0caffc7fbdfedb540574cad326e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
